import React from 'react';
import { motion } from 'framer-motion';
import useStore from '../store/useStore';
import { localizedName, t } from '../i18n';
import PremiumIcon from './PremiumIcon';

export default function DurationSheet() {
  const { selectedProduct, selectDuration, locale } = useStore();
  if (!selectedProduct) return null;
  const durations = selectedProduct.durations?.filter((duration) => duration.isActive) || [];
  const maxDiscount = durations.reduce((max, duration) => duration.originalPrice > duration.price ? Math.max(max, Math.round(((duration.originalPrice - duration.price) / duration.originalPrice) * 100)) : max, 0);
  const close = () => useStore.setState({ showDurationSheet: false });
  return <><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={close} className="fixed inset-0 bg-black/70 backdrop-blur-sm z-40" /><motion.div initial={{ y: '100%' }} animate={{ y: 0 }} exit={{ y: '100%' }} transition={{ type: 'spring', stiffness: 300, damping: 35 }} drag="y" dragConstraints={{ top: 0 }} dragElastic={0.2} onDragEnd={(_, info) => { if (info.offset.y > 120 || info.velocity.y > 500) close(); }} className="fixed bottom-0 left-0 right-0 z-50 bottom-sheet rounded-t-3xl max-h-[85vh] overflow-hidden flex flex-col"><div className="flex justify-center pt-3 pb-2"><div className="w-10 h-1.5 rounded-full bg-[#333]" /></div><div className="px-4 pb-3 border-b border-[#1a1a1a]"><div className="flex gap-3 items-start">{selectedProduct.logo ? <img src={selectedProduct.logo} alt={localizedName(selectedProduct, locale)} className="w-12 h-12 rounded-xl object-cover" /> : <PremiumIcon name="key" size="2.5rem" className="text-neon" />}<div className="flex-1"><h2 className="font-black text-white text-lg">{localizedName(selectedProduct, locale)}</h2>{maxDiscount > 0 && <span className="inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full bg-red/10 text-red border border-red/20 mt-1"><PremiumIcon name="skull" /> −{maxDiscount}%</span>}{selectedProduct.features?.slice(0, 3).map((feature, index) => <p key={index} className="text-xs text-muted">{feature.text}</p>)}</div></div></div><div className="p-4 overflow-y-auto flex-1"><p className="text-xs text-muted mb-3 font-semibold">{locale === 'en' ? 'Choose a duration:' : 'اختر المدة المناسبة:'}</p><div className="space-y-3">{durations.map((duration, index) => <DurationRow key={duration._id} duration={duration} index={index} locale={locale} onSelect={() => (duration.stockCount > 0 || duration.inStock) && selectDuration(duration)} />)}</div><p className="text-center text-[10px] text-muted mt-4">{t(locale, 'back')}</p></div></motion.div></>;
}
function DurationRow({ duration, index, locale, onSelect }) { const inStock = duration.stockCount > 0 || duration.inStock; const hasDiscount = duration.originalPrice > duration.price; const discount = hasDiscount ? Math.round(((duration.originalPrice - duration.price) / duration.originalPrice) * 100) : 0; return <motion.button type="button" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * 0.05 }} whileTap={{ scale: 0.97 }} onClick={onSelect} disabled={!inStock} className={`w-full rounded-2xl p-4 flex items-center justify-between border transition-all ${inStock ? 'bg-[#1a1a1a] border-border hover:border-neon/40' : 'bg-[#111] border-border/50 opacity-60'}`}><div className="text-right"><div className="flex items-center gap-2"><p className="font-bold text-white text-base">{localizedName(duration, locale)}</p>{discount > 0 && <span className="text-[9px] font-bold px-1.5 py-0.5 rounded bg-red/10 text-red">−{discount}%</span>}</div>{hasDiscount && <p className="text-xs text-muted line-through">${Number(duration.originalPrice).toFixed(2)}</p>}<p className="text-neon-blue font-black text-xl glow-blue">${Number(duration.price).toFixed(2)}</p></div><div className="flex flex-col items-end gap-2">{inStock ? <><span className="inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full bg-neon/10 text-neon border border-neon/20"><PremiumIcon name="check" /> {duration.stockCount > 99 ? '99+' : duration.stockCount} {t(locale, 'available')}</span><span className="bg-neon text-black text-xs font-bold px-4 py-2 rounded-xl inline-flex items-center gap-1"><PremiumIcon name="trophy" /> {locale === 'en' ? 'Select' : 'اختيار'}</span></> : <span className="text-[10px] font-bold px-3 py-1.5 rounded-xl bg-[#2a2a2a] text-muted">{locale === 'en' ? 'Out of stock' : 'غير متوفر'}</span>}</div></motion.button>; }
