import React, { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { normalizeLocale, t } from '../i18n';
import PremiumIcon from './PremiumIcon';

const TIPS = ['instantDelivery', 'featured', 'support', 'payBinance', 'browseGames'];
export default function LoadingScreen() {
  const locale = normalizeLocale(localStorage.getItem('locale') || 'ar'); const [tipIndex, setTipIndex] = useState(0);
  useEffect(() => { const interval = setInterval(() => setTipIndex((value) => (value + 1) % TIPS.length), 2200); return () => clearInterval(interval); }, []);
  return <div className="fixed inset-0 bg-black flex flex-col items-center justify-center z-50"><motion.div initial={{ scale: 0, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} transition={{ duration: 0.5 }} className="flex flex-col items-center gap-6"><div className="relative"><motion.div animate={{ rotate: 360 }} transition={{ duration: 2, repeat: Infinity, ease: 'linear' }} className="w-20 h-20 rounded-full" style={{ background: 'conic-gradient(from 0deg, #00ff88, #00cfff, transparent, #00ff88)', padding: '3px' }}><div className="w-full h-full rounded-full bg-black" /></motion.div><div className="absolute inset-0 flex items-center justify-center text-neon"><PremiumIcon name="key" size="2.4rem" /></div></div><div className="text-center"><h1 className="text-xl font-black text-white">{t(locale, 'brand')}</h1><p className="text-neon text-sm mt-1"><PremiumIcon name="bolt" /> {t(locale, 'instantDelivery')}</p></div><div className="h-12 flex items-center justify-center w-64"><AnimatePresence mode="wait"><motion.div key={tipIndex} initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -15 }} className="flex items-center gap-2 text-center"><PremiumIcon name={TIPS[tipIndex] === 'support' ? 'support' : TIPS[tipIndex] === 'payBinance' ? 'gem' : 'gamepad'} className="text-neon" /><p className="text-xs text-muted">{t(locale, TIPS[tipIndex])}</p></motion.div></AnimatePresence></div><div className="flex gap-3">{[0, 1, 2, 3, 4].map((i) => <motion.div key={i} animate={{ scale: [1, 1.6, 1], opacity: [0.2, 1, 0.2] }} transition={{ duration: 1.2, repeat: Infinity, delay: i * 0.15 }} className="w-2 h-2 rounded-full bg-neon" />)}</div></motion.div></div>;
}
